### PR TITLE
Remove unnecessary table classes

### PR DESCRIPTION
**Pull request by halvorsanden**
- Remove unnecessary table classes
- Wrap service portfolio tables in a shadow 🦹 (this won’t have an effect until https://github.com/bring/mybring-design-system/pull/982 is merged)

### CODE REVIEW

**Comment by WebDevBring** [comment]
[trello.com/c/E5C43AkZ](https://trello.com/c/E5C43AkZ)

**Review by Igor-J86 — APPROVED** [review]
Looks good!
The only thing is that the overflow-shadow-thingy is not working quite as expected in dark mode, but that‘s maybe something we can adjust later if needed. 😄

**Comment by halvorsanden** [comment]
> Looks good! The only thing is that the overflow-shadow-thingy is not working quite as expected in dark mode, but that‘s maybe something we can adjust later if needed. 😄

Ooouf, that’s something I should fix now 😬

**Comment by Igor-J86** [comment]
> > Looks good! The only thing is that the overflow-shadow-thingy is not working quite as expected in dark mode, but that‘s maybe something we can adjust later if needed. 😄
> 
> Ooouf, that’s something I should fix now 😬

Ahh, that was nice! Feel free to merge if ready! 👍🏼

**Pull request merged**
