### PR TITLE
Event Cast API: Add OAS sourced docs

### PR DESCRIPTION
**Pull request by eideeivindsen**
- [ ] [API update message](https://github.com/bring/developer-site#tips-for-writing-an-api-update-message) (changelog entry) has been reviewed by Mybring Experience.

### CODE REVIEW

**Comment by bringdev** [comment]
[trello.com/c/R3kJDlOr](https://trello.com/c/R3kJDlOr)

**Review by richas2 — APPROVED** [review]
Looks good 🎉

**Review by richas2 — DISMISSED** [review]
Think we should address these issues before putting this in prod
https://trello.com/c/JTNSTigH/823-event-cast-swagger-fixes

**Review by Tjellez — APPROVED** [review]
Regarding Richas comment, its all out now. So this should be good to merge

**Pull request merged**
