### PR TITLE
put general terms condition as a part of bring developer site so that…

### PR DESCRIPTION
**Pull request by manishatgithub**
put general terms condition as a part of bring developer site so that any other application can refer to it. don't think should be a be part of shipping guide.

### CODE REVIEW

**Comment by bringdev** [comment]
[trello.com/c/z7scbRBj](https://trello.com/c/z7scbRBj)

**Comment by manishatgithub** [comment]
I can't see this link in customer signup 🤔

**Comment by manishatgithub** [comment]
cleaning would be different task, can you approve if its ok.

**Comment by pankajagrawal16** [comment]
As long as you promise to do the cleanup in SG and update the link here https://www.mybring.com/signup/register/user , it sounds reasonable thing to do.

**Comment by pankajagrawal16** [comment]
Also why is content of https://api.bring.com/shippingguide/user/terms.pdf looks different than what we have here ? is that supposed to change ?

**Comment by manishatgithub** [comment]
bussines has came with new content which need to be updated.

**Comment by manishatgithub** [comment]
Also what is the entry point for https://www.mybring.com/signup/register/user I can't see it on the landing page of signup ?

**Comment by pankajagrawal16** [comment]
Its linked from dev site only as its supposed to be used by API users only.

**Pull request merged**
