### PR TITLE
Add light mode css for examples

### PR DESCRIPTION
**Pull request by Igor-J86**
Adding light mode CSS in the syntax.css, following the same logic as we have in place for the dark theme. So, when a user have dark mode enabled or selected, the original dark mode syntax highlighting CSS is in use, otherwise the newly added light mode CSS will be in use.

We can generate a syntax highlighting CSS with Hugo. In order to do so, we need to install Hugo locally.

Quick start:
https://gohugo.io/getting-started/quick-start/

Then we can generate one base on the available styles:

`hugo gen chromastyles --style=monokai > syntax.css`

Gallery of available styles.
https://xyproto.github.io/splash/docs/longer/all.html

I chose **rainbow_dash**, but modified it so the colours don't pop too much and have some balance between dark mode and light mode.

Chosen theme:
https://xyproto.github.io/splash/docs/longer/rainbow_dash.html

JSON example:
Skjermbilde 2022-10-13 kl  10 30 04

XML example:
Skjermbilde 2022-10-13 kl  10 33 31

### CODE REVIEW

**Comment by bringdev** [comment]
[trello.com/c/wLhLDE4G](https://trello.com/c/wLhLDE4G)

**Comment by halvorsanden** [comment]
I have mixed success with bold code fonts – but maybe it works better if we update the code font stack in MDS?
Screenshot 2022-10-13 at 10 39 31

**Comment by Igor-J86** [comment]
> I have mixed success with bold code fonts – but maybe it works better if we update the code font stack in MDS? Screenshot 2022-10-13 at 10 39 31

Oh, right.. This is the `font-weight: 700;` causing it, it seems...? I think maybe updating the code font stack in MDS will solve this, but we could also remove the `font-weight: 700;` from the syntax highlighting CSS as well. I don't see whether it is beneficial to have it there or not though...

**Review by halvorsanden — APPROVED** [review]
Feel free to merge, whether you remove the font-weight or look at the font stack first.
… and good work! 👍😁

**Pull request merged**
