### PR TITLE
Format request endpoint type and address

### PR DESCRIPTION
**Pull request by Igor-J86**
Skjermbilde 2022-02-25 kl  09 43 58

### CODE REVIEW

**Comment by bringdev** [comment]
[trello.com/c/8Bv9foYj](https://trello.com/c/8Bv9foYj)

**Comment by halvorsanden** [comment]
How about having the method outside the grey area, with a slight spacing between them? I think we could get rid of the border then and use the badges classes for the method (with extra padding).

Then we could make a blue one for POST when we get to that in the other APIs – and we already have a red one for DELETE.

**Comment by Igor-J86** [comment]
Agree.. Changed to:
Skjermbilde 2022-02-25 kl  10 26 10

**Review by halvorsanden — APPROVED** [review]
Looking good!

**Pull request merged**
