### PR TITLE
remove b ssh and show from docs

### PR DESCRIPTION
**Pull request by maur1**

### CODE REVIEW

**Comment by WebDevBring** [comment]
[trello.com/c/L3oGNig2](https://trello.com/c/L3oGNig2)

**Review by deepalimamtani3112 — COMMENTED** [review]
Just a small suggestion, on the same page , it also mentions about `ruby` in the line : `Currently there are scripts written in python, ruby and bash.` So Ruby can be removed from eher as no longer used.

**Review by deepalimamtani3112 — APPROVED** [review]

**Review by sharebear — COMMENTED** [review]
This is the source of the blog post published on the public developer site here https://developer.bring.com/blog/b-scripts/

Is there really value in updating 7 year old blog posts? Personally I think we could leave this as it was.

**Comment by maur1** [comment]
> This is the source of the blog post published on the public developer site here https://developer.bring.com/blog/b-scripts/
> 
> Is there really value in updating 7 year old blog posts? Personally I think we could leave this as it was.

Agreed, did not see it in its full context. Closing PR

**Pull request closed without merging**
