### PR TITLE
new update for SOAP decommissioning for both booking and shippingguide api

### PR DESCRIPTION
**Pull request by AnshikaKoul**
NOT TO BE MERGED TILL 10/05/2024

### CODE REVIEW

**Comment by tomgag** [comment]
Do we know when that email is generated? If it is monday 13th of May, perhaps merge this the friday before?

**Review by halvorsanden — APPROVED** [review]
I would consider not having the dates in bold as it doesn’t really do anything when the text is so short and clear anyway. But it’s up to you. I think this is well written.

**Comment by halvorsanden** [comment]
> Do we know when that email is generated? If it is monday 13th of May, perhaps merge this the friday before?

You can merge this the Friday before, or even earlier, just make sure the publish date is not set to a later date than the merge.

**Comment by AnshikaKoul** [comment]
> Do we know when that email is generated? If it is monday 13th of May, perhaps merge this the friday before?

@tomgag : 👇 from @halvorsanden :) 

Screenshot 2024-05-08 at 11 22 48

**Comment by AnshikaKoul** [comment]
will merge it on friday - 10.05.2024

**Pull request merged**
